Tienda/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.productos.urls')),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/productos/urls.py
from django.conf.urls import url

from apps.productos.views import ProductosTemplateView, ProductoCreateView, ProductosList, ProductoDetailView, \
    ProductoUpdateView, ProductoDeleteView

urlpatterns = [
    url(r'^productos_list_data/$', ProductosList.as_view(), name="productos_list_data"),
    url(r'^$', ProductosTemplateView.as_view(), name="lista_productos"),
    url(r'^nuevo/$', ProductoCreateView.as_view(), name="producto_nuevo"),
    url(r'^(?P<pk>\d+)/$', ProductoDetailView.as_view(), name="producto_detalle"),
    url(r'^(?P<pk>\d+)/editar$', ProductoUpdateView.as_view(), name="producto_editar"),
    url(r'^(?P<pk>\d+)/eliminar', ProductoDeleteView.as_view(), name="producto_eliminar"),
]

apps/productos/models.py
from django.core.exceptions import ValidationError
from django.db import models


class Categoria(models.Model):
    nombre = models.CharField(max_length=150)

    class Meta:
        db_table = "categorias"

    def __str__(self):
        return '{}'.format(self.nombre)


class Imagen(models.Model):
    def validate_file_extension(value):
        if not value.name.endswith('.jpg') or value.name.endswith('.jpeg'):
            raise ValidationError("Solo se permiten archivos JPG/JPEG")

    imagen = models.ImageField(upload_to="images/", validators=[validate_file_extension])

    class Meta:
        db_table = "imagenes"


class Producto(models.Model):
    nombre = models.CharField(max_length=150)
    descripcion = models.TextField()
    modelo = models.CharField(max_length=150)
    precio = models.DecimalField(decimal_places=2, max_digits=16)
    categoria = models.ManyToManyField(Categoria)
    imagenes = models.ManyToManyField(Imagen, blank=True, null=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    ultima_actualizacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{}".format(self.nombre)

apps/productos/forms.py
from django import forms
from multiupload.fields import MultiImageField

from apps.productos.models import Producto


class ProductoForm(forms.ModelForm):
    archivos = MultiImageField(min_num=1, max_num=10, max_file_size=1024 * 1024 * 5)

    class Meta:
        model = Producto
        fields = [
            'nombre',
            'descripcion',
            'modelo',
            'precio',
            'categoria',
            'archivos'
        ]


class ProductoEditForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = [
            'nombre',
            'descripcion',
            'modelo',
            'precio',
            'categoria'
        ]

apps/productos/views.py
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import TemplateView
from django.views.generic import UpdateView
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.conf import settings

from apps.productos.forms import ProductoForm, ProductoEditForm
from apps.productos.models import Producto, Imagen


class ProductosList(BaseDatatableView):
    model = Producto
    columns = ['nombre', 'modelo', 'precio', 'id']
    order_columns = ['nombre', 'modelo', 'precio', '']
    max_display_length = 250

    def render_column(self, row, column):
        if column == 'precio':
            return '$ {}'.format(row.precio)
        else:
            return super(ProductosList, self).render_column(row, column)

    def filter_queryset(self, qs):
        search = self.request.GET.get(u'search[value]', None)
        if search:
            qs = qs.filter(Q(nombre__icontains=search) |
                           Q(modelo__icontains=search) |
                           Q(precio__icontains=search)
                           )
        return qs


class ProductosTemplateView(TemplateView):
    template_name = "productos/lista_productos.html"


class ProductoCreateView(CreateView):
    model = Producto
    template_name = "productos/producto_nuevo.html"
    form_class = ProductoForm
    success_url = reverse_lazy("lista_productos")

    def form_valid(self, form):
        super(ProductoCreateView, self).form_valid(form)
        for archivo in form.cleaned_data['archivos']:
            img = Imagen.objects.create(imagen=archivo)
            form.instance.imagenes.add(img)
        messages.success(self.request, "Producto agregado éxitosamente")
        return HttpResponseRedirect(self.get_success_url())


    def form_invalid(self, form):
        return super(ProductoCreateView, self).form_invalid(form)


class ProductoDetailView(DetailView):
    model = Producto
    template_name = "productos/producto_detalle.html"

    def get_context_data(self, **kwargs):
        context = super(ProductoDetailView, self).get_context_data(**kwargs)
        context['MEDIA_URL'] = settings.MEDIA_URL
        return context


class ProductoUpdateView(UpdateView):
    model = Producto
    template_name = "productos/producto_editar.html"
    form_class = ProductoEditForm
    success_url = reverse_lazy("lista_productos")

    def form_valid(self, form):
        messages.success(self.request, "Producto Editado éxitosamente")
        return super(ProductoUpdateView, self).form_valid(form)

    def form_invalid(self, form):
        return super(ProductoUpdateView, self).form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super(ProductoUpdateView, self).get_context_data(**kwargs)
        context['MEDIA_URL'] = settings.MEDIA_URL
        return context


class ProductoDeleteView(DeleteView):
    model = Producto
    success_url = reverse_lazy("lista_productos")
    template_name = "productos/producto_eliminar.html"

templates/base.html
<!doctype html>
<html class="no-js" lang="es" dir="ltr">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "css/foundation.min.css" %}">
    <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "css/app.css" %}">
</head>
<body>

<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="example-menu"></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="example-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Tienda Web</li>

    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><a href="{% url "lista_productos" %}">Productos</a></li>
    </ul>
  </div>
</div>
<div class="row expanded ">
    {% if messages %}
        {% for message in messages %}
            <div {% if message.tags %}
                class="center callout {% if message.tags == 'error' %} alert {% endif %} {{ message.tags }}" {% endif %}
                data-animate="slide-in-left" data-closable="slide-out-right">
                <h6><i class="fa fa-exclamation-circle"></i> {{ message }} </h6>
                <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
        <br>
    {% endif %}
    {% block container %}

    {% endblock %}
</div>

<script src="{% static "js/vendor/jquery.js" %}"></script>
<script src="{% static "js/vendor/what-input.js" %}"></script>
<script src="{% static "js/vendor/foundation.min.js" %}"></script>
<script src="{% static "js/app.js" %}"></script>
{% block extra_css %}{% endblock %}
{% block extra_js %}{% endblock %}
{% block scripts %}
{% endblock %}
</body>
</html>

templates/form_snippet.html
{% for field in form %}
    {% if not field.is_hidden %}
        <div class="" id="{{ field.auto_id }}_field_group">
            <label class="">
                {{ field.label }}
                {% if field.field.required %}
                    <b style="color: red;">*</b>
                {% endif %}
            </label>
            <div class="">
                <ul class="">
                    {% for error in field.errors %}
                        <li style="color: red">{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="">
                {{ field }}
            </div>
            <div class="">
        <span class="">
            {{ field.help_text }}
        </span>
            </div>
        </div>
    {% else %}
        {{ field }}
    {% endif %}
{% endfor %}

templates/productos/lista_productos.html
{% extends "base.html" %}
{% block title %}
    Lista de Productos
{% endblock %}
{% block container %}
    <div class="row">

        <div class="columns small-12 large-10 large-centered">
            <div class="columns large-6">
                <h2 class="titulo">Lista de Productos</h2>

            </div>
            <div class="columns large-4 large-offset-2" >

                <a href="{% url "producto_nuevo" %}" class="button">Agregar</a>
            </div>
            <hr>
            <table id="productos_list" style="width: 100%">
                <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Modelo</th>
                    <th>Precio</th>
                    <th>Opciones</th>
                </tr>
                </thead>
            </table>
        </div>
    </div>
{% endblock %}
{% load staticfiles %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static "css/datatables.min.css" %}">
{% endblock %}
{% block extra_js %}
    <script src="{% static "js/datatables.min.js" %}"></script>
{% endblock %}
{% block scripts %}
    <script>
        $(document).ready(function () {
            $('#productos_list').dataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "{% url 'productos_list_data' %}",
                "columnDefs": [{
                    "targets": 3,
                    data: function (row) {
                        /* Agregamos un boton para detalles y eliminado del producto, (el pk viene de la vista)*/
                        return "<a class='button small primary' href='/productos/" + row[3] + "'>Ver más</a>";
                    }
                }],
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }
            });
        });
    </script>
{% endblock %}

templates/productos/producto_detalle.html
{% extends "base.html" %}
{% block title %}
    {{ producto.nombre }}
{% endblock %}
{% block container %}
    <div class="columns large-8 small-12 medium-10 large-centered medium-centered">
        <h2 class="titulo">{{ producto.nombre }}</h2>
        <hr>
        <div class="row">
            <div class="columns large-7 medium-6 small-12">
                <img id="main_img" src="{{ MEDIA_URL }}{{ producto.imagenes.first.imagen }}" alt="" width="350">
                <ul class="horizontal_img">
                    {% for img in producto.imagenes.all %}
                        <li>
                            <img src="{{ MEDIA_URL }}/{{ img.imagen }}" alt="{{ img.imagen }}" width="100"
                                 onclick="change_img('{{ MEDIA_URL }}/{{ img.imagen }}')">
                        </li>
                    {% endfor %}
                </ul>
                <hr>
            </div>


            <div class="columns large-5 medium-6 small-12">
                <ul>
                    <li><b>Modelo: </b><span class="color_marcado">{{ producto.modelo }}</span></li>
                    <li><b>Descripción:</b> <span>
                        {{ producto.descripcion | safe }}
                    </span>
                    </li>
                    <li><b>Agregado el: </b> <span class="color_marcado"> {{ producto.fecha_creacion }}</span></li>
                    <li><b>Precio:</b><span class="color_marcado"> ${{ producto.precio }}</span></li>
                </ul>
            </div>
        </div>

        <div class="button-group">
            <a class="button secondary" href="{% url "lista_productos" %}">Volver</a>
            <a class="button alert" href="{% url "producto_eliminar"  producto.id %}">Eliminar</a>
            <a class="button" href="{% url "producto_editar"  producto.id %}">Editar</a>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        var change_img = function (url) {
            $('#main_img').attr('src', url);
        }
    </script>
{% endblock %}

templates/productos/producto_editar.html
{% extends "base.html" %}
{% block title %}
    Editar {{ producto.nombre }}
{% endblock %}
{% block container %}
    <div class="columns small-12 large-6 medium-10 large-centered medium-centered">

        <h2 class="titulo">Editar {{ producto.nombre }}</h2>
        <hr>
        <form method="post">
            {% csrf_token %}
            {% include 'form_snippet.html' %}
            <h6>Imagenes</h6>
            {% for img in producto.imagenes.all %}
                <img src="{{ MEDIA_URL }}/{{ img.imagen }}" alt="">
            {% endfor %}

            <div class="button-group">
                <a class="button secondary" href="{% url "producto_detalle" producto.pk %}">Volver</a>
                <input class="button" type="submit" value="Editar">
            </div>

        </form>
    </div>
{% endblock %}
{% load staticfiles %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static "css/froala_editor.min.css" %}">
    <link rel="stylesheet" href="{% static "css/froala_style.min.css" %}">
{% endblock %}
{% block extra_js %}
    <script src="{% static "js/froala_editor.min.js" %}"></script>
    <script src="{% static "js/es.js" %}"></script>
{% endblock %}
{% block scripts %}
    <script>
        $(function () {
            $('#id_descripcion').froalaEditor({
                language: 'es',
                heightMin: 180,
                heightMax: 240
            })
        });
    </script>
{% endblock %}

templates/productos/producto_eliminar.html
{% extends "base.html" %}
{% block title %}
    Elimianr {{ producto.nombre }}
{% endblock %}
{% block container %}
    <div class="columns small-12 large-6 medium-10 large-centered medium-centered">

        <h2 class="titulo">Eliminar {{ producto.nombre }}</h2>
        <h4 class="subheader">Modelo {{ producto.modelo }}</h4>
        <hr>
        <form method="post">
            {% csrf_token %}
            <h5>¿Esta seguro de <b>Eliminar</b> este producto?</h5>
            <code>Este paso es irreversible</code>
            <hr>
            <div class="button-group">
                <a class="button secondary" href="{% url "producto_detalle" producto.pk %}">Volver</a>
                <input class="button alert" type="submit" value="Eliminar">
            </div>
        </form>
    </div>
{% endblock %}
{% load staticfiles %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static "css/froala_editor.min.css" %}">
    <link rel="stylesheet" href="{% static "css/froala_style.min.css" %}">
{% endblock %}
{% block extra_js %}
    <script src="{% static "js/froala_editor.min.js" %}"></script>
    <script src="{% static "js/es.js" %}"></script>
{% endblock %}
{% block scripts %}
    <script>
        $(function () {
            $('#id_descripcion').froalaEditor({
                language: 'es',
                heightMin: 180,
                heightMax: 240
            })
        });
    </script>
{% endblock %}

templates/productos/producto_nuevo.html
{% extends "base.html" %}
{% block title %}
    Nuevo Producto
{% endblock %}
{% block container %}
    <div class="columns small-12 large-6 medium-10 large-centered medium-centered">

    <h2 class="titulo">Nuevo producto</h2>
    <hr>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'form_snippet.html' %}
            <div class="button-group">
                <a class="button secondary" href="{% url "lista_productos" %}">Volver</a>
                <input class="button success" type="submit" value="Crear">
            </div>
        </form>
    </div>
{% endblock %}
{% load staticfiles %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static "css/froala_editor.min.css" %}">
    <link rel="stylesheet" href="{% static "css/froala_style.min.css" %}">
{% endblock %}
{% block extra_js %}
    <script src="{% static "js/froala_editor.min.js" %}"></script>
    <script src="{% static "js/es.js" %}"></script>
{% endblock %}
{% block scripts %}
    <script>
        $(function () {
            $('#id_descripcion').froalaEditor({
                language: 'es',
                heightMin: 180,
                heightMax: 240
            })
        });
    </script>
{% endblock %}